apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
data:
  squid.conf: |-
    {{- .Files.Get "squid.conf" | nindent 4 }}

    {{- if .Values.tlsOutgoingOptions.caFile }}
    tls_outgoing_options cafile={{ .Values.tlsOutgoingOptions.caFile }}
    {{- end }}

    {{- if .Values.cache.allowList }}
    {{- range .Values.cache.allowList }}
    acl cached_urls url_regex {{ . }}
    {{- end }}

    cache allow cached_urls
    cache deny all
    {{- else }}
    cache allow all
    {{- end }}

    # Use an asynchronous(aufs) disk cache (backed by a tmpfs memory volume)
    # Set storage limit at 80% of the total volume's size (per cache_dir docs)
    # Structure: 16 first-level directories, 256 second-level subdirectories
    cache_dir aufs /var/spool/squid/cache {{ mulf .Values.cache.memory.size 0.8 | int }} 16 256

    # Maximum object size to cache
    maximum_object_size {{ .Values.cache.memory.maxObjectSize }} MB
