{{- if .Values.squid.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "squid.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
  {{- if .Values.squidExporter.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.squidExporter.port }}"
    prometheus.io/path: "{{ .Values.squidExporter.metricsPath }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.trafficDistribution (semverCompare ">= 1.30.0-0" .Capabilities.KubeVersion.Version) }}
  trafficDistribution: {{ .Values.service.trafficDistribution }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.squidExporter.enabled }}
    - port: {{ .Values.squidExporter.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
    {{- if .Values.perSiteExporter.enabled }}
    - port: {{ .Values.perSiteExporter.port }}
      targetPort: per-site-http
      protocol: TCP
      name: per-site-http
    {{- end }}
  selector:
    {{- include "squid.selectorLabels" . | nindent 4 }}
{{- end }}
